version: "3.8"

services:
  createpost:
    image: "${DOCKERHUB_USERNAME}/app:createpost-latest"
    ports:
      - "3001:3000"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "${DYNAMODB_TABLE}"
      S3_BUCKET: "${S3_BUCKET}"

  getpost:
    image: "${DOCKERHUB_USERNAME}/app:getpost-latest"
    ports:
      - "3002:3000"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "${DYNAMODB_TABLE}"
      S3_BUCKET: "${S3_BUCKET}"

  updatepost:
    image: "${DOCKERHUB_USERNAME}/app:updatepost-latest"
    ports:
      - "3003:3000"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "${DYNAMODB_TABLE}"
      S3_BUCKET: "${S3_BUCKET}"

  deletepost:
    image: "${DOCKERHUB_USERNAME}/app:deletepost-latest"
    ports:
      - "3004:3000"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "${DYNAMODB_TABLE}"
      S3_BUCKET: "${S3_BUCKET}"